library(ggplot2)
library(tm)
library(gridExtra)
library(stringi)
library(knitr)
install.packages("RWeka")
library(RWeka)
wordcount_TweetTrain <- stri_count_words(reviews_train)
wordcount_ReviewTest <- stri_count_words(reviews_test)
data_linecount <- c(length(reviews_train), length(reviews_test))
data_wordcount <- c(sum(wordcount_TweetTrain), sum(wordcount_ReviewTest))
data_max_wordcount <- c(max(wordcount_TweetTrain), max(wordcount_ReviewTest))
data_avg_wordcount <- c(mean(wordcount_TweetTrain), mean(wordcount_ReviewTest))
data_summary <- data.frame(reviews, data_linecount, data_wordcount, data_max_wordcount, data_avg_wordcount)
data_names <- c("Dataset", "Line Count", "Total Word Count", "Max Word Count", "Average Word Count")
kable(data_summary, digits = 1, col.names = data_names, align = 'c')
